services:
  dejur-flow-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: niiadev/dejur-flow-front:latest
    container_name: dejur-flow-front
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:${PORT} || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - flowise

networks:
  flowise:
    external: true
