import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Building,
  Building2,
  Calendar,
  Check,
  CircleHelp,
  Clock3,
  Download,
  FilePlus,
  Files,
  FileText,
  Filter,
  LayoutDashboard,
  LogOut,
  MapPin,
  Moon,
  Pencil,
  Save,
  Search,
  Settings,
  Sparkles,
  Sun,
  Trash2,
  UploadCloud,
  User,
  Users,
  Wallet,
  X,
} from 'lucide-react';

export const spacingScale = [4, 8, 12, 16, 20, 24, 32, 40, 48, 64] as const;

export const radiusScale = {
  input: 'rounded-md',
  button: 'rounded-md',
  card: 'rounded-xl',
  dialog: 'rounded-xl',
  badge: 'rounded-full',
  tooltip: 'rounded-md',
  popover: 'rounded-md',
} as const;

export const iconMap: Record<string, LucideIcon | [LucideIcon, LucideIcon]> = {
  dashboard: LayoutDashboard,
  newRequest: FilePlus,
  requests: Files,
  pending: Clock3,
  approved: BadgeCheck,
  users: Users,
  settings: Settings,
  help: CircleHelp,
  ai: Sparkles,
  upload: UploadCloud,
  download: Download,
  reports: BarChart3,
  company: Building2,
  person: User,
  document: FileText,
  cnpj: Building,
  city: MapPin,
  calendar: Calendar,
  amount: Wallet,
  search: Search,
  filter: Filter,
  delete: Trash2,
  edit: Pencil,
  save: Save,
  cancel: X,
  confirm: Check,
  back: ArrowLeft,
  next: ArrowRight,
  logout: LogOut,
  theme: [Moon, Sun],
};
